name: CI-CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repo
        uses: actions/checkout@v4

      - name: Login a Docker Hub
        run: echo "${{ secrets.DOCKER_PASS }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USER }}/mi-app .

      - name: Test básico
        run: docker run ${{ secrets.DOCKER_USER }}/mi-app echo "BUILD OK"

      - name: Push a Docker Hub
        run: docker push ${{ secrets.DOCKER_USER }}/mi-app